sass:
  load_paths:
    - _sass

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

title: JieQi Yan
tagline: |
  M.S. Student in Environmental Policy and Management
description: |
  I'm JieQi Yan, a current graduate student at UC Davis's Environmental Policy Management Masters Program.
url: jieqiyan.com
favicon: /assets/images/favicon.png
keywords: jieqi,yan,jieqi yan,jqiyan@ucdavis.edu,jieqi.yan0606@gmail.com,epm,uc davis,ucd,masters,graduate student,environmental policy management,masters program,geology

author:
  name: JieQi Yan
  email: jieqi.yan0606@gmail.com
  url: https://jieqiyan.com/

logo: /assets/images/favicon.png

social:
  links:
    linkedin: https://www.linkedin.com/in/jieqiyan/

locale: en_US






